language: objective-c
before_install:
  - gem install xcpretty
install: echo
script:
  - export LC_CTYPE=en_US.UTF-8
  - set -o pipefail
  - xcodebuild -project 'Here Search.xcodeproj' -sdk iphonesimulator8.1 -configuration Debug -scheme 'Here Search' test | xcpretty -c
